export const DATA_PROVIDERS = [
  {
    name: 'India Meteorological Department (IMD)',
    abbr: 'IMD',
    role: 'Rainfall observations, district warnings, nowcast, QPF',
    url: 'https://mausam.imd.gov.in',
    license: 'Government of India Open Data',
  },
  {
    name: 'Central Water Commission (CWC)',
    abbr: 'CWC',
    role: 'River gauge stations, flood forecasts, advisory levels',
    url: 'https://cwc.gov.in',
    license: 'Government of India Open Data',
  },
  {
    name: 'ISRO / NRSC — Bhuvan',
    abbr: 'ISRO',
    role: 'Flood hazard GIS layers, satellite inundation maps',
    url: 'https://bhuvan.nrsc.gov.in',
    license: 'NRSC Open Data Archive',
  },
  {
    name: 'NASA / JAXA — GPM IMERG',
    abbr: 'NASA',
    role: 'Global satellite rainfall, 30-min, 0.1° resolution',
    url: 'https://gpm.nasa.gov',
    license: 'NASA Open Data',
  },
  {
    name: 'Open-Meteo / GloFAS (ECMWF + Copernicus)',
    abbr: 'GloFAS',
    role: 'River discharge forecasts, ensemble predictions',
    url: 'https://open-meteo.com',
    license: 'CC BY 4.0',
  },
  {
    name: 'GDACS — Global Disaster Alert and Coordination System',
    abbr: 'GDACS',
    role: 'International disaster event feeds, severity scores',
    url: 'https://gdacs.org',
    license: 'CC BY 4.0',
  },
  {
    name: 'IIT Delhi HydroSense Lab — INDOFLOODS',
    abbr: 'IIT-D',
    role: 'India historical flood database, catchment attributes',
    url: 'https://hydrosense.iitd.ac.in',
    license: 'Academic open data',
  },
  {
    name: 'HydroSHEDS / WWF',
    abbr: 'HydroSHEDS',
    role: 'River networks, basin boundaries, flow accumulation',
    url: 'https://hydrosheds.org',
    license: 'HydroSHEDS License',
  },
  {
    name: 'India WRIS / NHP',
    abbr: 'WRIS',
    role: 'River basin GIS, reservoir levels, hydrological data',
    url: 'https://indiawris.gov.in',
    license: 'Government of India Open Data',
  },
];
